/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-MIB-RECEIVER"
 * 	found in "nr_mib_receiver.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "BCCH-BCH-Message.h"

static asn_oer_constraints_t asn_OER_type_message_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_message_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_message_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_BCH_Message__message, choice.mib),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mib"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_message_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* mib */
};
static asn_CHOICE_specifics_t asn_SPC_message_specs_2 = {
	sizeof(struct BCCH_BCH_Message__message),
	offsetof(struct BCCH_BCH_Message__message, _asn_ctx),
	offsetof(struct BCCH_BCH_Message__message, present),
	sizeof(((struct BCCH_BCH_Message__message *)0)->present),
	asn_MAP_message_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_message_2 = {
	"message",
	"message",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_message_constr_2, &asn_PER_type_message_constr_2, CHOICE_constraint },
	asn_MBR_message_2,
	1,	/* Elements count */
	&asn_SPC_message_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BCCH_BCH_Message_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_BCH_Message, message),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_message_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"message"
		},
};
static const ber_tlv_tag_t asn_DEF_BCCH_BCH_Message_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BCCH_BCH_Message_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* message */
};
static asn_SEQUENCE_specifics_t asn_SPC_BCCH_BCH_Message_specs_1 = {
	sizeof(struct BCCH_BCH_Message),
	offsetof(struct BCCH_BCH_Message, _asn_ctx),
	asn_MAP_BCCH_BCH_Message_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BCCH_BCH_Message = {
	"BCCH-BCH-Message",
	"BCCH-BCH-Message",
	&asn_OP_SEQUENCE,
	asn_DEF_BCCH_BCH_Message_tags_1,
	sizeof(asn_DEF_BCCH_BCH_Message_tags_1)
		/sizeof(asn_DEF_BCCH_BCH_Message_tags_1[0]), /* 1 */
	asn_DEF_BCCH_BCH_Message_tags_1,	/* Same as above */
	sizeof(asn_DEF_BCCH_BCH_Message_tags_1)
		/sizeof(asn_DEF_BCCH_BCH_Message_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BCCH_BCH_Message_1,
	1,	/* Elements count */
	&asn_SPC_BCCH_BCH_Message_specs_1	/* Additional specs */
};

