/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-MIB-RECEIVER"
 * 	found in "nr_mib_receiver.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_BCCH_BCH_Message_H_
#define	_BCCH_BCH_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MIB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BCCH_BCH_Message__message_PR {
	BCCH_BCH_Message__message_PR_NOTHING,	/* No components present */
	BCCH_BCH_Message__message_PR_mib
} BCCH_BCH_Message__message_PR;

/* BCCH-BCH-Message */
typedef struct BCCH_BCH_Message {
	struct BCCH_BCH_Message__message {
		BCCH_BCH_Message__message_PR present;
		union BCCH_BCH_Message__message_u {
			MIB_t	 mib;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BCCH_BCH_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BCCH_BCH_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _BCCH_BCH_Message_H_ */
#include <asn_internal.h>
