/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_BCH_Message;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module NR-MIB-RECEIVER in nr_mib_receiver.asn */
	&asn_DEF_BCCH_BCH_Message,	
	0
};

